### ISSUE TITLE
Can we able to deploy project wise 

### ISSUE THREAD

**Issue by KalanaPerera** [tscheiki/ElasticDeploy#3]
Can we able to deploy project wise 

Example : when we run this code 

> elasticdeploy deploy 

it will deploy all the projects know 

is there something like this

> elasticdeploy project1 deploy

Thanks

**Comment by tscheiki** [comment]
The main purpose of this project is to deploy multiple projects on a single Elastic Beanstalk environment. In your case you don't need ElasticDeploy and you can use the basic functionality of the EB CLI (http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3.html). 

Please let me know if you need anything else.

**Comment by KalanaPerera** [comment]
Thanks for the reply, 

Actually, I also need to deploy multiple projects on Elastic Beanstalk,

I will tell my problem,


I have project like below structure 

example.com -> main git repo
example.com/cms -> different repo
example.com/backend -> different repo
example.com/project3 -> different repo 

so I need to build project wise, hope you can understand.

Thanks again

**Comment by tscheiki** [comment]
Yeah that works. However, to deploy multiple projects on Elastic Beanstalk you need to upload all projects once. ElasticDeploy creates one .zip file with all your projects and uploads them afterwards. 

Does that work for you?
